"""changed post table, added image column

Revision ID: 119546378b4d
Revises: 287ab8c38109
Create Date: 2023-07-26 14:00:38.633516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119546378b4d'
down_revision = '287ab8c38109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
